### ISSUE TITLE
Documentation needs to be updated to reflect the changes to `takePhotos()` in cherri

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherrilang.org#1]
Some changes were recently made relative to this issue: https://github.com/electrikmilk/cherri/issues/26, but the docs are yet to reflect this.

Update: My bad, this seems to have been updated without a pill request.

**Comment by electrikmilk** [comment]
Fixed with [64ea9ca](https://github.com/electrikmilk/cherrilang.org/commit/64ea9cae87a5adbbf690838e916efe0760d714c8) and [3ca3b75](https://github.com/electrikmilk/cherrilang.org/commit/3ca3b750c16d4e4f6f2bbd60298fc41c0d3f1e5f).

**Comment by electrikmilk** [comment]
@mikeogezi No worries, thanks for pointing this out!
